services:

  database:
      image: postgres:16-alpine
      container_name: "database"
      command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
      volumes:
        - ./db-data/postgresql:/var/lib/postgresql/data
        # -- Any script we put under scripts will be copied to the container and run when our database gets initialized
        #  - ./scripts:/docker-entrypoint-initdb.d 
      ports:
        - "127.0.0.1:5431:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s  
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      restart: always
      networks:
        - back-tier
      # tmpfs: /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - database
    user: '$UID:$GID'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:3333:80"
    volumes:
      - ./db-data/pgadmin:/var/lib/pgadmin
    networks:
      - back-tier

networks:
  back-tier: